version: '3.8'

services:
  primary:
    container_name: primary
    image: postgres:14-alpine
    ports:
      - "9432:5432"
    environment:
      POSTGRES_USER: primary
      POSTGRES_PASSWORD: primary
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
  standby:
    container_name: standby
    image: postgres:14-alpine
    ports:
      - "9442:5432"
    environment:
      POSTGRES_USER: standby
      POSTGRES_PASSWORD: standby
